title: "ProductTaxon"
type: "object"
properties:
    main:
        type: "string"
        example: "MAIN_TAXON_CODE"
    others:
        type: "array"
        items:
            type: string
            example: "OTHER_TAXON_CODE"