title: "ProductReviewsPage"
allOf:
- $ref: '#/definitions/Page'
- type: object
  properties:
      title:
          type: "string"
          example: "Nice mug"
      rating:
          type: "integer"
          example: 5
      comment:
          type: "string"
          example: "It is a really nice mug."
      author:
          type: "string"
          example: "example@shop.com"