get:
    tags:
    - "products"
    summary: "Show a product with the given code."
    description: "This endpoint will return a product with the given code."
    operationId: "productDetailsByCode"
    consumes:
    - "application/json"
    produces:
    - "application/json"
    parameters:
    - name: "code"
      in: "path"
      description: "Code of expected product. Example: AWESOME_KING_ARTHURS_MUG"
      required: true
      type: "string"
    - name: "channel"
      in: "query"
      description: "Channel from which products should be gathered. Example: en_GB"
      required: true
      type: "string"
    - name: "locale"
      in: "query"
      description: "Locale in which products should be shown. Example: en_GB"
      required: false
      type: "string"
    responses:
        200:
            description: "OK"
            schema:
                type: "object"
                $ref: "#/definitions/ProductDetails"